### ISSUE TITLE
Shoobox.io link redirects to Heroku "not found" page

### ISSUE THREAD

**Issue by nickgnd** [davydovanton/awesome-hanami#20]
Hi, thanks for your work! Really helpful.

This issue only to report that the link to [Shoobox.io](http://www.shoobox.io/) seems broken or maybe the application is no longer active.

Have a nice day :)

**Comment by davydovanton** [comment]
You're right. Thanks!

@jxxcarlson could you help us with this problem? 😊

**Comment by davydovanton** [comment]
We deleted this app from list
