### ISSUE TITLE
hanami-rethinkdb won't work with "modern" Hanami versions

### ISSUE THREAD

**Issue by katafrakt** [davydovanton/awesome-hanami#32]
hanami-rethinkdb is built agains old `Hanami::Model` versions built on Sequel and does not work with ROM backend. [rom-rethinkdb](https://github.com/rom-rb/rom-rethinkdb) should be used instead. I'm not sure if it's better to remove it completely or clearly mark that it works with versions `< 0.9` only.

**Comment by davydovanton** [comment]
Thanks for the issue. I think we need to mark this gem and add information about rom-rethinkdb 👍

**Comment by davydovanton** [comment]
I marked that this gem works only with `< 0.9` version. Thanks!
