### ISSUE TITLE
Adding gems which do not have rails dependencies

### ISSUE THREAD

**Issue by onemanstartup** [davydovanton/awesome-hanami#4]
Many people looking for rails alternative and rails plugins alternatives. It will be great if there was a section with vanilla ruby gems.
It can be serving as todo list for making integration libraries for hanami.
Also many features can be provided with rack libraries. It will be great if alongside with those libraries would be manual about how to integrate those rack apps.

**Comment by davydovanton** [comment]
done, you can find information here:
https://github.com/davydovanton/awesome-hanami#vanilla-libraries-and-hanami
