### ISSUE TITLE
Make website?

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/awesome-hanami#9]

**Comment by jodosha** [comment]
@davydovanton Please do. We can use the fund that we raise to pay the domain.

**Comment by bruz** [comment]
@davydovanton have you seen [Flatdoc](http://ricostacruz.com/flatdoc/)? It's what http://awesome-ruby.com/ uses to take the original awesome list markdown on github and render it into that site.

**Comment by davydovanton** [comment]
@bruz thanks for link, i'll look on this 👍

**Comment by davydovanton** [comment]
So, I created simple site. you can find link here: http://blog.davydovanton.com/awesome-hanami/

Now we need to solve problem with domain. @jodosha what do you think? Can we use subdomain from hanami for this?

**Comment by jodosha** [comment]
@davydovanton If you agree, I can buy awesome-hanami.com.

**Comment by bruz** [comment]
@davydovanton that's looking good! Nice work.

**Comment by davydovanton** [comment]
@jodosha if you want to buy `awesome-hanami.com` do it. Also I can buy domain too :)

**Comment by jodosha** [comment]
@davydovanton Ok this is your project, you should own it. 😉

**Comment by davydovanton** [comment]
http://awesome-hanami.org
